name: Nitro Type Tracker
on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tracker
        run: python3 app.py
